# Welcome to Python 101

These notes will shortly be availible for your consumption.

Most of this is stolen from
https://github.com/rajathkumarmp/Python-Lectures

In [110]:
2+2  #I'm adding 2 and 2 !!!

4

In [9]:
xy = 'Hey'
x=3
y=2

In [14]:
print (x)

3


| Symbol | Task Performed |
|----|---|
| +  | Addition |
| -  | Subtraction |
| /  | division |
| %  | mod |
| *  | multiplication |
| //  | floor division |
| **  | to the power of |

In [10]:
print (xy, x , x*x, x**2, x**4, x+y, x-y, x/y, x//y)

Hey 3 9 9 81 5 1 1.5 1


Floor division is nothing but converting the result so obtained to the nearest integer.

Bitwise operators

| Symbol | Task Performed |
|----|---|
| == | True, if it is equal |
| !=  | True, if not equal to |
| < | less than |
| > | greater than |
| <=  | less than or equal to |
| >=  | greater than or equal to |

In [12]:
z = 1

In [13]:
z == 1

True

In [15]:
z > 1

False

In [17]:
print (pow(3,4))

81


In [23]:
print (list(range(2,40,4)))

[2, 6, 10, 14, 18, 22, 26, 30, 34, 38]


### Loop

In [31]:
for i in range(2,40,4):
    print (i)

2
6
10
14
18
22
26
30
34
38


In [32]:
type (z)

int

In [40]:
type (xy)

str

In [33]:
print ("Hello world")

Hello world


In [38]:
string1 = "! - Fk Matlab !"

In [39]:
print ("Hello world %s" %string1 )

Hello world ! - Fk Matlab !


In [41]:
print ("Hello %d world" %z)

Hello 1 world


In [42]:
print ("lol" * 10)

lollollollollollollollollollol


In [43]:
print ("lol \n" * 10)

lol 
lol 
lol 
lol 
lol 
lol 
lol 
lol 
lol 
lol 



In [49]:
a = ['apple','orange','pear']
print (type(a))
print (a)

<class 'list'>
['apple', 'orange', 'pear']


## In python life starts at zero... Indexing

In [50]:
a[0]

'apple'

In [51]:
a[-1]

'pear'

In [52]:
a[1]

'orange'

In [54]:
y=['pens','pencils']
z=[a,y]
print (z)

[['apple', 'orange', 'pear'], ['pens', 'pencils']]


In [57]:
z[0][0]

'apple'

## Slicing lists

In [58]:
num = [0,1,2,3,4,5,6,7,8]

In [60]:
print (num[0:4])

[0, 1, 2, 3]


In [64]:
len (num)

9

In [65]:
min (num)

0

In [66]:
max (num)

8

### Dictionaries
Works abit like a list, but can assign its own indexing style i.e. set keys and values

In [68]:
d0={}
d0['one']= 3000
d0['OneTwo'] = 999
print (d0)

{'one': 3000, 'OneTwo': 999}


In [73]:
names = ['One', 'Two', 'Three', 'Four', 'Five']
numbers = [1, 2, 3, 4, 5]
d2 = dict(zip(names,numbers))

In [76]:
print (d2)
print (d2.keys())
print (d2.values())

{'One': 1, 'Two': 2, 'Three': 3, 'Four': 4, 'Five': 5}
dict_keys(['One', 'Two', 'Three', 'Four', 'Five'])
dict_values([1, 2, 3, 4, 5])


### Control statements

In [79]:
x = 10
y = 12
if x > y:
    print ("x>y")
elif x < y:
    print ("x<y")
    if x==10:
        print ("x=10")
    else:
        print ("invalid")
else:
    print ("x=y")

x<y
x=10


### While

In [80]:
i = 1
while i < 10:
    print(i ** 2)
    i = i+1
print('Bye')

1
4
9
16
25
36
49
64
81
Bye


### Functions

In [82]:
def firstfunc():
    print ("Hey hydromodellers!")
    print ("Modellers, whats poppin'?") 

In [83]:
firstfunc()

Hey hydromodellers!
Modellers,whats poppin'?


Lets have it accept some arguments to make it actually useful in some capacity.
Note the use of the + to concatenate

In [85]:
def firstfunc(username):
    print ("Hey", username + "!")
    print (username, ", whats poppin'?") 

In [87]:
name1 = input('Please enter your name : ')

Please enter your name : Guy


In [88]:
firstfunc(name1)

Hey Guy!
Guy , whats poppin'?


In [90]:
def firstfunc(username):
    print ("Hey", username + '!')
    print (username + ',' ,"How do you do?")
def secondfunc():
    name = input("Please enter your name : ")
    firstfunc(name)

In [91]:
secondfunc()

Please enter your name : guido
Hey guido!
guido, How do you do?


### Return

In [95]:
def times(x,y):
    '''This multiplies the two input arguments'''
    z = x*y
    return z

In [96]:
c = times(4,5)
print (c)

20


In [97]:
help(times)

Help on function times in module __main__:

times(x, y)
    This multiplies the two input arguments



In [98]:
help (print)

Help on built-in function print in module builtins:

print(...)
    print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)
    
    Prints the values to a stream, or to sys.stdout by default.
    Optional keyword arguments:
    file:  a file-like object (stream); defaults to the current sys.stdout.
    sep:   string inserted between values, default a space.
    end:   string appended after the last value, default a newline.
    flush: whether to forcibly flush the stream.



In [99]:
import numpy as np

In [102]:
a = np.array([1, 2, 3])   # Create a rank 1 array

In [103]:
print(type(a))            # Prints "<class 'numpy.ndarray'>"
print(a.shape)           
print(a[0], a[1], a[2])   
a[0] = 5                  
print(a)  

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]


In [104]:
b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b.shape)

(2, 3)


In [108]:
c = np.ones((10,10))
print(c)

[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]


Notes on functions

There are two kinds of functions (actually one is technically a method but we'll ignore that). One kind of function takes an argument by putting that argument inside the parentheses. For example - len("mystring") will return 8 because there are 8 letters in "mystring". (See footnote one for slightly more detail)

Another kind of function is one that is specific to a type or class of objects. An example of a class is List. An example of a List is [1,2,3,4]. The class List has functions defined that work specifically on Lists. To use those functions on a specific List we would use dot notation. For example, to use the special function append on a List called my_list we would write my_list.append(insert_thing_to_append). (See footnote 2 for a little more)

Hope that is a simpler way of explaining it. You will come across dot notation by functions for Lists, Dictionaries and Strings quite often. You will also use them for user-defined classes and even for using specific functions from modules and libraries.

Footnotes:

1. len is an example of a function that is defined in the __builtin__ namespace which is the environment you are working in. Almost everything in Python is actually an object and therefore part of a class or a module. So technically len and other such built-in global functions are part of the __builtin__ module. Not important to know though...

2. There are many kinds of built-in classes, the most common being List, String and Dict. Each of these builtin classes have associated methods that are defined in the source code.

3. In general, dot notation tells Python to look inside the space that is before the dot for code to execute. You can use dot notation to access the specific version of a certain function that is defined in a different class or a different module. For example, if I have one module that is called basicmath and another called advancedmath and they both have constants PI, but with different values, then I would call basicmath.PI to get that version of PI, and advancedmath.PI to get its version of PI.